insert into Countries (Name) values ('Portugal');
insert into Countries (Name) values ('Croatia');
insert into Countries (Name) values ('Sweden');
insert into Countries (Name) values ('France');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Thailand');
insert into Countries (Name) values ('Canada');
insert into Countries (Name) values ('Peru');
insert into Countries (Name) values ('Czech Republic');
insert into Countries (Name) values ('South Korea');
insert into Countries (Name) values ('Thailand');
insert into Countries (Name) values ('Bosnia and Herzegovina');
insert into Countries (Name) values ('France');
insert into Countries (Name) values ('Argentina');
insert into Countries (Name) values ('Ukraine');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Armenia');
insert into Countries (Name) values ('Sweden');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Thailand');
insert into Countries (Name) values ('Zambia');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Croatia');
insert into Countries (Name) values ('Peru');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('China');
insert into Countries (Name) values ('Indonesia');
insert into Countries (Name) values ('Spain');
insert into Countries (Name) values ('Dominica');
go

insert into Cities (Name, CountryId) values ('Chemerivtsi', 25);
insert into Cities (Name, CountryId) values ('Jönköping', 18);
insert into Cities (Name, CountryId) values ('Radeče', 2);
insert into Cities (Name, CountryId) values ('Pasireurih', 27);
insert into Cities (Name, CountryId) values ('Bongbong', 25);
insert into Cities (Name, CountryId) values ('Zili', 7);
insert into Cities (Name, CountryId) values ('Beverwijk', 28);
insert into Cities (Name, CountryId) values ('Puerto López', 30);
insert into Cities (Name, CountryId) values ('Wotan', 25);
insert into Cities (Name, CountryId) values ('Dengfeng', 24);
insert into Cities (Name, CountryId) values ('Manyana', 19);
insert into Cities (Name, CountryId) values ('Patao', 8);
insert into Cities (Name, CountryId) values ('Xinle', 7);
insert into Cities (Name, CountryId) values ('Qimantage', 23);
insert into Cities (Name, CountryId) values ('Privolzhskiy', 17);
insert into Cities (Name, CountryId) values ('Tessaoua', 5);
insert into Cities (Name, CountryId) values ('Lufang', 15);
insert into Cities (Name, CountryId) values ('Siliana', 3);
insert into Cities (Name, CountryId) values ('Kavallári', 29);
insert into Cities (Name, CountryId) values ('Rumilly', 22);
insert into Cities (Name, CountryId) values ('Garden Grove', 21);
insert into Cities (Name, CountryId) values ('Leskovac', 7);
insert into Cities (Name, CountryId) values ('Chase', 8);
insert into Cities (Name, CountryId) values ('Karpogory', 22);
insert into Cities (Name, CountryId) values ('Sobral da Adiça', 11);
insert into Cities (Name, CountryId) values ('Dulangan', 8);
insert into Cities (Name, CountryId) values ('Los Angeles', 20);
insert into Cities (Name, CountryId) values ('Wan’an', 16);
insert into Cities (Name, CountryId) values ('Jinping', 20);
insert into Cities (Name, CountryId) values ('Tiabaya', 28);
insert into Cities (Name, CountryId) values ('Ponggok', 27);
insert into Cities (Name, CountryId) values ('Rožna Dolina', 20);
insert into Cities (Name, CountryId) values ('Skopin', 22);
insert into Cities (Name, CountryId) values ('Sapotskin', 28);
insert into Cities (Name, CountryId) values ('Diamantino', 3);
insert into Cities (Name, CountryId) values ('Comilla', 23);
insert into Cities (Name, CountryId) values ('Villeneuve-la-Garenne', 4);
insert into Cities (Name, CountryId) values ('Kaustinen', 22);
insert into Cities (Name, CountryId) values ('Delson', 16);
insert into Cities (Name, CountryId) values ('Circasia', 18);
insert into Cities (Name, CountryId) values ('Balakliya', 1);
insert into Cities (Name, CountryId) values ('Tranca', 15);
insert into Cities (Name, CountryId) values ('Lubbock', 21);
insert into Cities (Name, CountryId) values ('Shilong', 29);
insert into Cities (Name, CountryId) values ('Karangsuko', 14);
insert into Cities (Name, CountryId) values ('Cloyne', 5);
insert into Cities (Name, CountryId) values ('Registro', 14);
insert into Cities (Name, CountryId) values ('Banī Suhaylā', 26);
insert into Cities (Name, CountryId) values ('Kengyuan', 3);
insert into Cities (Name, CountryId) values ('Liulihe', 4);
insert into Cities (Name, CountryId) values ('Rudnogorsk', 18);
insert into Cities (Name, CountryId) values ('Middelburg', 8);
insert into Cities (Name, CountryId) values ('Huangludian', 30);
insert into Cities (Name, CountryId) values ('Omaha', 14);
insert into Cities (Name, CountryId) values ('Saiki', 12);
insert into Cities (Name, CountryId) values ('Popayán', 22);
insert into Cities (Name, CountryId) values ('Tía Juana', 25);
insert into Cities (Name, CountryId) values ('Xiekou', 19);
insert into Cities (Name, CountryId) values ('Lazarevac', 28);
insert into Cities (Name, CountryId) values ('Songyuan', 23);
insert into Cities (Name, CountryId) values ('Thị Trấn Tân Yên', 10);
insert into Cities (Name, CountryId) values ('Nurmo', 14);
insert into Cities (Name, CountryId) values ('Tall Rif‘at', 29);
insert into Cities (Name, CountryId) values ('Galitsy', 3);
insert into Cities (Name, CountryId) values ('Vera', 15);
insert into Cities (Name, CountryId) values ('Yangqiao', 21);
insert into Cities (Name, CountryId) values ('Hajnówka', 6);
insert into Cities (Name, CountryId) values ('Lawepakam', 14);
insert into Cities (Name, CountryId) values ('Nacimiento', 27);
insert into Cities (Name, CountryId) values ('Brčko', 3);
insert into Cities (Name, CountryId) values ('Sukarama', 5);
insert into Cities (Name, CountryId) values ('Staryy Krym', 5);
insert into Cities (Name, CountryId) values ('Zarzal', 5);
insert into Cities (Name, CountryId) values ('Centenario', 1);
insert into Cities (Name, CountryId) values ('Botshabelo', 24);
insert into Cities (Name, CountryId) values ('Blois', 7);
insert into Cities (Name, CountryId) values ('Orléans', 12);
insert into Cities (Name, CountryId) values ('Sremska Mitrovica', 3);
insert into Cities (Name, CountryId) values ('Bagumbayan', 23);
insert into Cities (Name, CountryId) values ('Roa', 18);
insert into Cities (Name, CountryId) values ('Thívai', 10);
insert into Cities (Name, CountryId) values ('Solčava', 15);
insert into Cities (Name, CountryId) values ('Bo Kluea', 25);
insert into Cities (Name, CountryId) values ('Czarnocin', 29);
insert into Cities (Name, CountryId) values ('Torrance', 11);
insert into Cities (Name, CountryId) values ('Sandouping', 16);
insert into Cities (Name, CountryId) values ('Krylovskaya', 3);
insert into Cities (Name, CountryId) values ('Mujur', 18);
insert into Cities (Name, CountryId) values ('Prómachoi', 14);
insert into Cities (Name, CountryId) values ('Huage', 26);
insert into Cities (Name, CountryId) values ('Zhifang', 29);
insert into Cities (Name, CountryId) values ('Murcki', 20);
insert into Cities (Name, CountryId) values ('Niverville', 5);
insert into Cities (Name, CountryId) values ('Datong', 18);
insert into Cities (Name, CountryId) values ('Stockton', 9);
insert into Cities (Name, CountryId) values ('Bourges', 25);
insert into Cities (Name, CountryId) values ('Guaíba', 23);
insert into Cities (Name, CountryId) values ('Bairro do Margaça', 24);
insert into Cities (Name, CountryId) values ('Maqbanah', 15);
insert into Cities (Name, CountryId) values ('Xinghua', 20);
go

insert into Airplanes (Model, MaxPassangers) values ('300ZX', 178);
insert into Airplanes (Model, MaxPassangers) values ('Familia', 211);
insert into Airplanes (Model, MaxPassangers) values ('CL-Class', 118);
insert into Airplanes (Model, MaxPassangers) values ('Fit', 133);
insert into Airplanes (Model, MaxPassangers) values ('Yukon', 369);
insert into Airplanes (Model, MaxPassangers) values ('Viper', 369);
insert into Airplanes (Model, MaxPassangers) values ('Shadow', 237);
insert into Airplanes (Model, MaxPassangers) values ('Tracer', 313);
insert into Airplanes (Model, MaxPassangers) values ('LTD Crown Victoria', 292);
insert into Airplanes (Model, MaxPassangers) values ('S2000', 201);
insert into Airplanes (Model, MaxPassangers) values ('Solara', 306);
insert into Airplanes (Model, MaxPassangers) values ('Enclave', 266);
insert into Airplanes (Model, MaxPassangers) values ('Ram 1500', 181);
insert into Airplanes (Model, MaxPassangers) values ('Navajo', 65);
insert into Airplanes (Model, MaxPassangers) values ('Rodeo Sport', 307);
insert into Airplanes (Model, MaxPassangers) values ('Solara', 312);
insert into Airplanes (Model, MaxPassangers) values ('Rally Wagon 2500', 50);
insert into Airplanes (Model, MaxPassangers) values ('1500', 376);
insert into Airplanes (Model, MaxPassangers) values ('E-Class', 335);
insert into Airplanes (Model, MaxPassangers) values ('A8', 188);
go

insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2020-01-07', 15, 20, 18);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2020-03-14', 2, 28, 48);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-01-16', 11, 16, 24);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-10-08', 1, 31, 62);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-12-22', 2, 27, 99);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2022-02-25', 5, 80, 79);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-12-21', 16, 33, 76);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-09-03', 3, 61, 84);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2020-09-03', 10, 8, 90);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2022-01-28', 13, 36, 27);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-07-16', 11, 7, 85);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-12-26', 18, 31, 34);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2022-03-29', 17, 35, 76);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-11-26', 4, 35, 59);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-05-24', 11, 19, 91);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-04-29', 19, 58, 76);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2020-10-10', 11, 3, 91);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-11-02', 11, 52, 59);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2021-04-12', 20, 45, 7);
insert into Flights (Date, AirplaneId, DepartureCityId, ArrivalCityId) values ('2019-09-22', 15, 82, 38);
go